version: '3'
services:
  crowi:
    build:
      context: .
      args:
        NODE_ENV: "development"
    tty: true
    environment:
      DEBUG: "crowi:*"
      PASSWORD_SEED: "password"
      MONGO_URI: mongodb://mongodb:27017/crowi
      FILEUPLOAD: local
    volumes:
      - ./:/crowi
      - /crowi/node_modules
    ports:
      - 3000:3000
      links:
        - mongodb
    command: bash -c "npm install && npm start"

  mongodb:
    image: mongo:3.6.3
    volumes:
      - ./data/mongodb:/data/db
    restart: always
    ports:
      - 27017:27017
