version: '3'
services:
  crowi:
    build: .
    tty: true
    environment:
      - DEBUG="crowi:*"
      - PASSWORD_SEED="password"
      - MONGO_URI="mongodb://mongodb:27017/crowi"
      - FILEUPLOAD="local"
      - HTTP_PROXY="http://proxy.noc.kochi-tech.ac.jp:3128"
      - HTTPS_PROXY="http://proxy.noc.kochi-tech.ac.jp:3128"
      - http_proxy="http://proxy.noc.kochi-tech.ac.jp:3128"
      - https_proxy="http://proxy.noc.kochi-tech.ac.jp:3128"
    volumes:
      - ./:/crowi
      - /crowi/node_modules
    ports:
      - 3000:3000
    links:
      - mongodb
    command: bash -c "npm install --unsafe-perm && PASSWORD_SEED=$PASSWORD_SEED MONGO_URI=$MONGO_URI npm start"

  mongodb:
    image: mongo:3.6.3
    volumes:
      - ./data/mongodb:/data/db
    restart: always
    ports:
      - 27017:27017
